SUPESC-334 Adyen SOFORT Payment is not authorized correctly
spryker-eco/adyen pull request #38
Opened 2021-04-22 10:30 UTC by kkicheglovspryker

- Developer(s): @kkicheglovspryker 

- Ticket: https://spryker.atlassian.net/browse/SUPESC-334

- Academy PR: -

- Release Group: 

- merge: merge

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   Adyen                 | minor                 |                       |

-----------------------------------------

#### Module Adyen

##### Change log

Improvements

- Added order status check and skip redefinition
- Added test for this case

2021-04-26 08:39 UTC, AsonUnique commented on tests/SprykerEcoTest/Zed/Adyen/Business/FacadeTest.php
> +        $facade = $this->createFacade();
Please, add `// Arrange // Act // Assert` comments. 
Check for example `Bundles/StockAddress/tests/SprykerTest/Zed/StockAddress/Business/StockAddressFacadeTest.php`

2021-04-26 08:42 UTC, AsonUnique approved these changes

2021-04-26 10:02 UTC, romanhavrylko approved these changes

2021-04-26 11:39 UTC, volodymyr-nakvasiuk approved these changes

2021-04-27 06:27 UTC, abitskil commented on tests/SprykerEcoTest/Zed/Adyen/Business/FacadeTest.php
> +            // Assert
* Remove this `//Assert`.

2021-04-27 06:33 UTC, abitskil commented on src/SprykerEco/Zed/Adyen/Business/Handler/Redirect/OnlineTransferRedirectHandler.php
> +        $defaultOmsStatus = $this->getOmsStatus();
* Extract to the method `resolveOmsStatus()`.

2021-04-27 06:40 UTC, abitskil requested changes
Rewrite the change logs in the context of the public API:
* Adjusted `AdyenFacade::handleOnlineTransferResponseFromAdyen(),AdyenFacade::handleCreditCard3dResponseFromAdyen()`.
* Use the documentation https://spryker.atlassian.net/wiki/spaces/CORE/pages/523730976/Release+Notes+and+Changelogs.

Fix the code sniffer error:
* `Every API public method must also contain the {@inheritDoc} tag in docblock.`.

Fix the `phpstan` failing.

2021-05-13 14:25 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/Payment/CreditCardPaymentMapperPlugin.php
> +     *
* Add an `@api` mark to a method.
* Do the same for a similar places.

2021-05-13 14:45 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/Payment/CreditCardPaymentMapperPlugin.php
> +     *
Enable GitHub actions by a copy them from a repository: 
* https://github.com/spryker-eco/avalara-tax-product-option/pull/3/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f

2021-05-18 11:52 UTC, abitskil commented on .github/workflows/ci.yml
> +#       suite-tests:
* Remove commented part.

2021-05-18 11:59 UTC, abitskil commented on .github/workflows/ci.yml
> +jobs:
* Copy the content from https://github.com/spryker-eco/loggly/blob/master/.github/workflows/ci.yml.

2021-05-27 07:14 UTC, dmytro-sokolovskyi approved these changes

2021-05-28 12:43 UTC, abitskil commented on src/SprykerEco/Service/Adyen/Dependency/Service/AdyenToUtilTextServiceInterface.php
> +    public function hashValue($value, string $algorithm): string;
The bridge method must have the same signature as the method that it uses.

2021-05-28 12:43 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Dependency/Service/AdyenToUtilEncodingServiceInterface.php
> +    public function encodeJson(array $value, ?int $options = null, ?int $depth = null): ?string;
Same issue as above.

2021-05-28 12:45 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/Provider/AdyenControllerProvider.php
> +    protected function defineControllers(Application $app): void
Undo the change.

2021-05-28 12:47 UTC, abitskil commented on src/SprykerEco/Zed/Adyen/Dependency/Facade/AdyenToCalculationFacadeInterface.php
> +    public function recalculateOrder(OrderTransfer $orderTransfer): OrderTransfer;
Same issues as above.

2021-05-31 06:20 UTC, abitskil commented on src/SprykerEco/Client/Adyen/Dependency/Client/AdyenToZedRequestClientInterface.php
> +    public function call(string $url, TransferInterface $object, $requestOptions = null): TransferInterface;
Checke the original method.

2021-05-31 06:21 UTC, abitskil commented on src/SprykerEco/Service/Adyen/Dependency/Service/AdyenToUtilTextServiceInterface.php
> +    public function hashValue($value, $algorithm): string;
Same.

2021-05-31 06:22 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/Payment/CreditCardPaymentMapperPlugin.php
> +     * {@inheritDoc}
* It should be higher than specification.

2021-05-31 06:24 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/Payment/CreditCardPaymentMapperPlugin.php
> +     *  - Sets CreditCard payment data to Quote.
* Wrap names in backticks.
* Check other places.

2021-05-31 06:25 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/StepEngine/AdyenAliPaySubFormPlugin.php
> +     * - Creates AliPay subform DataProvider.
data provider.

2021-05-31 06:27 UTC, abitskil commented on src/SprykerEco/Zed/Adyen/Dependency/Facade/AdyenToSalesFacadeInterface.php
> +    public function getOrderByIdSalesOrder(int $idSalesOrder);
Remove the type hint.

2021-06-02 12:22 UTC, abitskil commented on src/SprykerEco/Client/Adyen/Dependency/Client/AdyenToZedRequestClientInterface.php
> +    public function call($url, TransferInterface $object, $requestOptions = null): TransferInterface;
* Remove the return type hint.

2021-06-02 12:48 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Dependency/Client/AdyenToQuoteClientInterface.php
> +    public function getQuote(): QuoteTransfer;
* Remove the return type hint.

2021-06-02 12:49 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Dependency/Client/AdyenToQuoteClientInterface.php
> +    public function setQuote(QuoteTransfer $quoteTransfer): void;
* Remove the return type hint.

2021-06-02 12:49 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Dependency/Service/AdyenToUtilEncodingServiceInterface.php
> +    public function encodeJson($value, $options = null, $depth = null): ?string;
* Remove the return type hint.

2021-06-02 12:54 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/Payment/KlarnaInvoicePaymentMapperPlugin.php
> +     * Specification:
* The word `Specification` is not needed in this case.
* The specification should go right after `{@inheritDoc}`.
*` \Spryker\Service\ProductConfigurationStorage\Plugin\PriceProduct\ProductConfigurationPriceProductVolumeFilterPlugin`

2021-06-03 06:55 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/StepEngine/AdyenDirectDebitSubFormPlugin.php
> +     * {@inheritDoc}
* Remove this line.

2021-06-03 06:55 UTC, abitskil commented on src/SprykerEco/Yves/Adyen/Plugin/StepEngine/AdyenDirectDebitSubFormPlugin.php
> +     * {@inheritDoc}
* Remove this line.

2021-06-03 07:14 UTC, abitskil approved these changes

2021-06-22 10:24 UTC, merged